-- 03. example계정으로 접속해서 테이블 정의서를 참고하여 MEMBER 테이블과 BOARD 테이블을 생성한다.


CREATE TABLE MEMBER(
	MEMBER_NO NUMBER PRIMARY KEY, -- PK 자체에 NOT NULL 조건 존재
	MEMBER_ID VARCHAR2(30) NOT NULL,
	MEMBER_PASSWORD VARCHAR2(30) NOT NULL,
	PHONE_NUMBER VARCHAR2(20),
	DELETE_YN CHAR(1) DEFAULT 'N' CHECK(DELETE_YN IN ('Y','N'))
);

COMMENT ON COLUMN MEMBER.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PW IS '비밀번호';
COMMENT ON COLUMN MEMBER.PHONE_NUMBER IS '핸드폰번호';
COMMENT ON COLUMN MEMBER.DELETE_YN IS '삭제여부';

SELECT * FROM MEMBER;


CREATE TABLE BOARD(
	BOARD_NO NUMBER PRIMARY KEY,
	BOARD_TITLE VARCHAR2(300) NOT NULL,
	BOARD_CONTENT VARCHAR2(4000) NOT NULL,
	BOARD_WRITER NUMBER REFERENCES MEMBER,	
	CREATE_DATE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN BOARD.BOARD_NO IS '글번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '글제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '글내용';
COMMENT ON COLUMN BOARD.BOARD_WRITER IS '작성자';
COMMENT ON COLUMN BOARD.CREATE_DATE IS '작성일자';

SELECT * FROM BOARD;


-- 04. MEMBER 테이블과 BOARD 테이블에 다음과 같은 데이터를 추가한다.
-- 단, 회원번호와 글번호는 시퀀스를 생성하여 추가한다.
-- 시퀀스 :
-- SEQ_MEMBER_NO : 100부터 시작하여 100씩 증가
-- SEQ_BOARD_NO : 1부터 시작하여 1씩 증가


-- MEMBER 테이블

-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO
START WITH 100
INCREMENT BY 100
;

--SELECT SEQ_MEMBER_NO.NEXTVAL FROM DUAL; 
--SELECT SEQ_MEMBER_NO.CURRVAL FROM DUAL;

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PASSWORD, PHONE_NUMBER)
VALUES (SEQ_MEMBER_NO.NEXTVAL,'step1','step11','-');
INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PASSWORD, PHONE_NUMBER)
VALUES (SEQ_MEMBER_NO.NEXTVAL,'step2','step22','010-1111-2222');
INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PASSWORD, PHONE_NUMBER)
VALUES (SEQ_MEMBER_NO.NEXTVAL,'step3','step33','-');

SELECT * FROM MEMBER ORDER BY MEMBER_NO;

--DELETE FROM MEMBER;
--DROP SEQUENCE SEQ_MEMBER_NO;


-- BOARD 테이블

-- 시퀀스 생성
CREATE SEQUENCE SEQ_BOARD_NO
START WITH 1
INCREMENT BY 1
;

SELECT SEQ_BOARD_NO.NEXTVAL FROM DUAL; 

INSERT INTO BOARD
VALUES (SEQ_BOARD_NO.NEXTVAL,'첫 글','스텝평가', 100, DEFAULT);
INSERT INTO BOARD
VALUES (SEQ_BOARD_NO.NEXTVAL,'두 번째 글','재밌다', 300, DEFAULT);
INSERT INTO BOARD
VALUES (SEQ_BOARD_NO.NEXTVAL,'세 번째 글','하하하', 200, DEFAULT);

--SELECT * FROM BOARD ORDER BY BOARD_NO;
--DELETE FROM BOARD;
--DROP SEQUENCE SEQ_BOARD_NO;

-- 05. 다음과 같은 결과를 조회할 수 있도록 SELECT문을 작성한다.
SELECT BOARD_NO 글번호, BOARD_TITLE 제목, BOARD_CONTENT 내용, MEMBER_ID 작성자, TO_CHAR(CREATE_DATE,'YY/MM/DD') 작성일
FROM BOARD
JOIN MEMBER ON(MEMBER_NO = BOARD_WRITER)
ORDER BY 글번호 DESC;




